---
- name: Set timezone
  timezone:
    name: "{{ timesync_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
    masked: no
  
- name: Check if NTP Service Exists
  stat: 
    path: /etc/init.d/ntp
  register: ntp_status
  
- name: Disable NTP service
  service:
    name: ntp
    enabled: no
    state: stopped
  when: ntp_status.stat.exists
